agent_params:
  buffer_size: 10000
  batch_size: 128
  epsilon: 0.30
  gamma: 0.99
  learning_rate: 0.0001
  tau: 0.005
  epsilon_min : 0.05
  epsilon_decay : 2000
  input_type : "multiframe"
  n_frames : 2
network_params:
  - Conv2d : [2,32,2,1]
  - ReLU : []
  - Conv2d : [32,64,2,1]
  - ReLU : []
  - Conv2d : [64,64, 2, 1]
  - ReLU : []
  - Flatten : [1,-1]
  - Linear : [3136,512]
  - ReLU : []
  - Linear : [512,4]
training_params:
  HuberLoss : []
  AdamW : [lr: 0.0001, amsgrad: True]