agent_params:
  buffer_size: 20000
  batch_size: 128
  epsilon: 0.25
  gamma: 0.99
  learning_rate: 0.0001
  tau: 0.005
  epsilon_min : 0.05
  epsilon_decay : 1000
network_params:
  - Linear: [100,100]
  - Sigmoid: []
  - Linear: [100,50]
  - Sigmoid: []
  - Linear: [50,50]
  - Sigmoid: []
  - Linear : [50,50]
  - Sigmoid: []
  - Linear: [50,4]
training_params:
  HuberLoss : []
  AdamW : [lr: 0.0001, amsgrad: True]