agent_params:
  epsilon: 0.1
  gamma: 0.99
  lambda_: 0.0
  learning_rate: 0.0001
  subset_actions: True
network_params:
  - Linear: [100,50]
  - Linear: [50,50]
  - Linear: [50,1]
training_params:
  MSELoss : []
  SGD : [lr: 0.0001]